source "https://rubygems.org"

ruby '3.1.2'

gem "rest-client"
gem "dotenv-rails"
gem "ridgepole"
gem "pry"
gem 'jwt'
gem 'firebase-admin'
gem 'dotenv-rails'
gem 'pry-rails'
gem "rails", "~> 7.1.2"
gem "mysql2"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "byebug", platforms: %i[ mri mingw x64_mingw ]

group :development, :test do
  gem "debug", platforms: %i[ mri ]
end

group :development do
  # gem "spring"
end

gem "tzinfo-data", platforms: %i[ x64_mingw jruby ]
gem "bootsnap", require: false
