
source "https://rubygems.org"

ruby '3.2.3'

gem "rest-client"
gem "ridgepole"
gem "pry"
gem 'jwt'
gem 'firebase-admin'
gem 'dotenv-rails'
gem 'pry-rails'
gem "rails", "~> 7.1.2"
gem 'mysql2', '~> 0.5.5'
gem "puma", ">= 5.0"
gem "rack-cors"
gem "byebug", platforms: %i[ mri mingw x64_mingw ]
gem 'google-cloud-storage'
gem 'firebase'
gem 'jbuilder'
gem "ruby-vips"
gem "image_processing"
gem 'mini_magick'
gem "bcrypt"
gem "counter_culture"
gem "aws-sdk-s3"
gem 'fog-aws'
gem 'unicorn'
gem 'active_model_serializers', '~> 0.10.0'

group :development, :test do
  gem "debug", platforms: %i[ mri ]
  gem 'rspec-rails', '~> 6.0.0'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'shoulda-matchers', '~> 6.0'
  gem 'rails-controller-testing'
end

group :development do
  # gem "spring"
end

gem "tzinfo-data", platforms: %i[ x64_mingw jruby ]
gem "bootsnap", require: false

gem "factory_bot", "~> 6.4"
