source "https://rubygems.org"

ruby '3.2.3'

gem "rest-client"
gem "ridgepole"
gem "pry"
gem 'jwt'
gem 'firebase-admin'
gem 'dotenv-rails'
gem 'pry-rails'
gem "rails", "~> 7.1.2"
gem 'mysql2', '~> 0.5.5'
gem "puma", ">= 5.0"
gem "rack-cors"
gem "byebug", platforms: %i[ mri mingw x64_mingw ]
gem 'google-cloud-storage'
gem 'firebase'
gem 'jbuilder'
gem "ruby-vips"
gem "image_processing"
gem 'mini_magick'




group :development, :test do
  gem "debug", platforms: %i[ mri ]
end

group :development do
  # gem "spring"
end

gem "tzinfo-data", platforms: %i[ x64_mingw jruby ]
gem "bootsnap", require: false
